add_newline = true
command_timeout=1000

[battery]
full_symbol = "ğŸ”‹"
charging_symbol = "ğŸ”Œ"
discharging_symbol = "âš¡"

[git_branch]
symbol = "ğŸŒ± "

[git_metrics]
disabled = true
added_style = "bold blue"

[git_status]
ahead = "â¤´ï¸"
behind = "â¤µï¸"
diverged = "ğŸ˜µ"
up_to_date = "âœ“"
untracked = "ğŸ¤·"
stashed = "ğŸ“¦"
modified = "ğŸ–‹ï¸"
staged = '[++\($count\)](green)'
renamed = "ğŸ”„"
deleted = "ğŸ—‘"
conflicted = "ğŸ™… "

[cmd_duration]
min_time = 10_000  # Show command duration over 10,000 milliseconds (=10 sec)
format = " took [$duration]($style)"

[hostname]
ssh_only = false
format = "<[$hostname]($style)>"
trim_at = "-"
style = "bold dimmed white"
disabled = true

[python]
python_binary = ["python3", "python2", "python"]
style = "bold green"
pyenv_version_name = true
detect_folders = [ "venv" ]

[package]
disabled = true


